_wandb:
    value:
        cli_version: 0.21.3
        e:
            hftnan7cq8pflxmcgpri43yr2s46dfz2:
                args:
                    - --no-log
                codePath: examples\showcase_3d_viz_example.py
                codePathLocal: examples\showcase_3d_viz_example.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "1004769636352"
                        used: "897102540800"
                email: christian.cooper.us@gmail.com
                executable: C:\Users\chris\nanochatAquaRat\.venv\Scripts\python.exe
                git:
                    commit: 2214d25d08cbe86b99885174984ea91f83595fa1
                    remote: https://github.com/HarleyCoops/nanochatAquaRat.git
                host: PC
                memory:
                    total: "16749838336"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\chris\nanochatAquaRat\examples\showcase_3d_viz_example.py
                python: CPython 3.10.15
                root: C:\Users\chris\nanochatAquaRat
                startedAt: "2025-10-25T14:48:47.280210Z"
                writerId: hftnan7cq8pflxmcgpri43yr2s46dfz2
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.15
            "5": 0.21.3
            "8":
                - 3
            "10":
                - 21
            "12": 0.21.3
            "13": windows-amd64
demo:
    value: attention_visualization
